#!/usr/bin/env bash

# Check if Nginx is running
nginx_status=$(service nginx status | grep -o "active (running)")
if [ -z "$nginx_status" ]; then
    echo "Nginx is not running. Starting Nginx..."
    service nginx start
else
    echo "Nginx is already running."
fi

# Check if Nginx is listening on port 80
nginx_listen=$(ss -tln | grep ":80 ")
if [ -z "$nginx_listen" ]; then
    echo "Configuring Nginx to listen on port 80..."
    sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
    service nginx restart
else
    echo "Nginx is already listening on port 80."
fi
