#!/usr/bin/env bash
# This script creates an RSA key pair with specific requirements

# Usage: ./1-create_ssh_key_pair

# Create an RSA key pair with 4096 bits
# -b flag specifies the number of bits in the key
# -f flag specifies the filename of the key pair
# -N flag specifies the passphrase to protect the key
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N 'betty'

# Output success message
echo "RSA key pair created successfully."
