#!/usr/bin/env bash
# SSH client configuration file

# Specify the host
Host your_server_ip
    # Use the private key ~/.ssh/school
    IdentityFile ~/.ssh/school
    
    # Refuse to authenticate using a password
    PasswordAuthentication no
